// ══════════════════════════════════════════════════════════════════════════════
// ArCoreSupportChecker
// Google ki official supported devices list se check karta hai
// Usage: ArCoreSupportChecker.isSupported(manufacturer, model)
// ══════════════════════════════════════════════════════════════════════════════

class ArCoreSupportChecker {
  // ── Supported devices list ─────────────────────────────────────────────────
  // Format: 'manufacturer|model' — sab lowercase
  static const Set<String> _supportedDevices = {
    // Asus
    'asus|rog phone',
    'asus|rog phone ii',
    'asus|rog phone iii',
    'asus|rog phone 5',
    'asus|rog phone 6 (ai2201)',
    'asus|rog phone 6d ultimate (ai2201)',
    'asus|rog phone 7 (ai2205)',
    'asus|rog phone 8 series',
    'asus|rog phone 9',
    'asus|zenfone 6',
    'asus|zenfone 7/7 pro',
    'asus|zenfone 8',
    'asus|zenfone 9',
    'asus|zenfone 10 (ai2302)',
    'asus|zenfone ar',
    'asus|zenfone ares',

    // CMF by Nothing
    'cmf by nothing|cmf by nothing phone 1',

    // Google
    'google|nexus 5x',
    'google|nexus 6p',
    'google|pixel',
    'google|pixel xl',
    'google|pixel 2',
    'google|pixel 2 xl',
    'google|pixel 3',
    'google|pixel 3 xl',
    'google|pixel 3a',
    'google|pixel 3a xl',
    'google|pixel 4',
    'google|pixel 4 xl',
    'google|pixel 4a',
    'google|pixel 4a 5g',
    'google|pixel 5',
    'google|pixel 5a 5g',
    'google|pixel 6',
    'google|pixel 6a',
    'google|pixel 6 pro',
    'google|pixel 7',
    'google|pixel 7a',
    'google|pixel 7 pro',
    'google|pixel 8',
    'google|pixel 8 pro',
    'google|pixel fold',
    'google|pixel tablet',

    // Honor
    'honor|honor 70',
    'honor|honor 90',
    'honor|honor 200',
    'honor|honor 200 pro',
    'honor|honor 400',
    'honor|honor 400 pro',
    'honor|honor magic vs',
    'honor|honor magic v2',
    'honor|honor magic v3',
    'honor|honor magic4 pro',
    'honor|honor magic5',
    'honor|honor magic5 pro',
    'honor|honor magic6 lite 5g',
    'honor|honor magic7 lite',
    'honor|honor x9c smart',

    // Huawei
    'huawei|honor 8x',
    'huawei|honor 10',
    'huawei|honor v20',
    'huawei|mate 20 lite',
    'huawei|mate 20',
    'huawei|mate 20 pro',
    'huawei|mate 20 x',
    'huawei|nova 3',
    'huawei|nova 3i',
    'huawei|nova 4',
    'huawei|p20',
    'huawei|p20 pro',
    'huawei|p30',
    'huawei|p30 pro',

    // Infinix
    'infinix mobile|gt 10 pro',
    'infinix mobile|gt 30 pro',
    'infinix mobile|hot 40 pro',
    'infinix mobile|hot 50 pro+',
    'infinix mobile|hot 60 pro+',
    'infinix mobile|infinix hot 60i',
    'infinix mobile|infinix hot 60 pro',
    'infinix mobile|infinix zero 40',
    'infinix mobile|infinix zero 40 5g',
    'infinix mobile|infinix zero flip',
    'infinix mobile|note 50 pro',
    'infinix mobile|note 50 pro+ 5g',
    'infinix mobile|note 50s 5g',
    'infinix mobile|note 50x 5g',
    'infinix mobile|note 11 pro',
    'infinix mobile|note 11s',
    'infinix mobile|note 12 2023',
    'infinix mobile|note 12 vip',
    'infinix mobile|note 30',
    'infinix mobile|note 30 pro',
    'infinix mobile|note 30 5g',
    'infinix mobile|note 30i',
    'infinix mobile|note 40',
    'infinix mobile|note 40 pro',
    'infinix mobile|zero 5g',
    'infinix mobile|zero 5g 2023',
    'infinix mobile|zero 20',
    'infinix mobile|zero 30',
    'infinix mobile|zero 30 5g',
    'infinix mobile|zero ultra',
    'infinix mobile|zero x',
    'infinix mobile|zero x pro',
    'infinix mobile|zero x neo',

    // LG
    'lg|g6',
    'lg|g8 thinq',
    'lg|g8x thinq',
    'lg|k92',
    'lg|k71',
    'lg|q92',
    'lg|stylo 7',
    'lg|v30',
    'lg|v30+',
    'lg|v35 thinq',
    'lg|v50 thinq',
    'lg|v50s thinq',
    'lg|v60 thinq',
    'lg|v60 thinq 5g',
    'lg|velvet 5g',
    'lg|velvet 2 pro',
    'lg|wing 5g',

    // Motorola
    'motorola|moto g⁵ˢ plus',
    'motorola|moto g⁶',
    'motorola|moto g⁶ plus',
    'motorola|moto g⁸',
    'motorola|moto g⁸ play',
    'motorola|moto g⁸ plus',
    'motorola|moto g⁸ power',
    'motorola|moto g⁸ power lite',
    'motorola|moto g⁹ plus',
    'motorola|moto g⁹ power',
    'motorola|moto g 5g',
    'motorola|moto g 5g (2022)',
    'motorola|moto g power',
    'motorola|moto g power (2021)',
    'motorola|moto g power 5g (2023)',
    'motorola|moto g pro',
    'motorola|moto g stylus',
    'motorola|moto g stylus (2021)',
    'motorola|moto g stylus (2023)',
    'motorola|moto g stylus 5g (2022)',
    'motorola|moto g stylus 5g (2023)',
    'motorola|moto g stylus 5g',
    'motorola|moto g stylus 5g (2025)',
    'motorola|moto g(50) 5g',
    'motorola|moto g(100)',
    'motorola|moto g24',
    'motorola|moto g32',
    'motorola|moto g34 5g',
    'motorola|moto g35 5g',
    'motorola|moto g42',
    'motorola|moto g51 5g',
    'motorola|moto g52',
    'motorola|moto g53',
    'motorola|moto g53 5g',
    'motorola|moto g54 5g',
    'motorola|moto g55 5g',
    'motorola|moto g62 5g',
    'motorola|moto g71 5g',
    'motorola|moto g72',
    'motorola|moto g73 5g',
    'motorola|moto g75 5g',
    'motorola|moto g82 5g',
    'motorola|moto g84 5g',
    'motorola|moto g200 5g',
    'motorola|motorola edge (2021)',
    'motorola|motorola edge (2022)',
    'motorola|motorola edge (2023)',
    'motorola|motorola edge',
    'motorola|motorola edge s',
    'motorola|motorola edge plus',
    'motorola|motorola edge plus (2022)',
    'motorola|motorola edge 20 pro',
    'motorola|motorola edge 20',
    'motorola|motorola edge 20 lite',
    'motorola|motorola edge 30',
    'motorola|motorola edge 30 fusion',
    'motorola|motorola edge 30 neo',
    'motorola|motorola edge 30 pro',
    'motorola|motorola edge 30 ultra',
    'motorola|motorola edge 40',
    'motorola|motorola edge 40 neo',
    'motorola|motorola edge 50 neo',
    'motorola|motorola edge 60 fusion',
    'motorola|motorola edge 60 stylus',
    'motorola|motorola one 5g',
    'motorola|motorola one fusion',
    'motorola|motorola one fusion+',
    'motorola|motorola one hyper',
    'motorola|motorola razr(2020)',
    'motorola|motorola razr(2022)',
    'motorola|motorola razr 40',
    'motorola|motorola razr 40 ultra',
    'motorola|moto x40',

    // Nothing
    'nothing|nothing phone (1)',
    'nothing|nothing phone (2)',
    'nothing|nothing phone (2) pro',
    'nothing|nothing phone (2a)',
    'nothing|nothing phone (2a) plus',
    'nothing|nothing phone (3a)',

    // OnePlus
    'oneplus|oneplus 6',
    'oneplus|oneplus 6t',
    'oneplus|oneplus 7',
    'oneplus|oneplus 7 pro',
    'oneplus|oneplus 7 pro 5g',
    'oneplus|oneplus 7t',
    'oneplus|oneplus 7t pro',
    'oneplus|oneplus 8',
    'oneplus|oneplus 8 pro',
    'oneplus|oneplus 8t',
    'oneplus|oneplus 9',
    'oneplus|oneplus 9 pro',
    'oneplus|oneplus 9r',
    'oneplus|oneplus 9rt 5g',
    'oneplus|oneplus 10 pro',
    'oneplus|oneplus 10 pro 5g',
    'oneplus|oneplus 10r 5g',
    'oneplus|oneplus 10t 5g',
    'oneplus|oneplus 11 5g',
    'oneplus|oneplus 11r 5g',
    'oneplus|oneplus 12',
    'oneplus|oneplus 13',
    'oneplus|oneplus 13r',
    'oneplus|oneplus 13s',
    'oneplus|oneplus 13t',
    'oneplus|oneplus ace 5',
    'oneplus|oneplus n10',
    'oneplus|oneplus nord',
    'oneplus|oneplus nord 2 5g',
    'oneplus|oneplus nord 2t 5g',
    'oneplus|oneplus nord 3 5g',
    'oneplus|oneplus nord 5',
    'oneplus|oneplus nord ce',
    'oneplus|oneplus nord ce 2 lite 5g',
    'oneplus|oneplus nord ce 3 5g',
    'oneplus|oneplus nord n20 5g',
    'oneplus|oneplus nord n200 5g',
    'oneplus|oneplus open',
    'oneplus|oneplus pad',
    'oneplus|nord ce5',

    // Oppo
    'oppo|a77 5g',
    'oppo|a78 5g',
    'oppo|a79 5g',
    'oppo|a94',
    'oppo|a96 5g',
    'oppo|a3 pro 5g',
    'oppo|a5 pro 5g',
    'oppo|f19 pro+',
    'oppo|f21 pro 5g',
    'oppo|f21s pro 5g',
    'oppo|f27 pro+ 5g',
    'oppo|f29 5g',
    'oppo|find n2 flip',
    'oppo|find n3',
    'oppo|find n3 flip',
    'oppo|find n5',
    'oppo|find x2',
    'oppo|find x2 pro',
    'oppo|find x3 pro',
    'oppo|find x5',
    'oppo|find x5 pro',
    'oppo|find x6 pro',
    'oppo|find x8',
    'oppo|find x8 pro',
    'oppo|k12 plus',
    'oppo|k12x 5g',
    'oppo|k13 5g',
    'oppo|pad 2',
    'oppo|pad 3 pro',
    'oppo|reno3 5g',
    'oppo|reno4 se 5g',
    'oppo|reno5',
    'oppo|reno5 a',
    'oppo|reno5 pro 5g',
    'oppo|reno5 pro+ 5g',
    'oppo|reno7 a',
    'oppo|reno7 5g',
    'oppo|reno7 pro 5g',
    'oppo|reno7 z 5g',
    'oppo|reno8 t',
    'oppo|reno8 t 5g',
    'oppo|reno 10 5g',
    'oppo|reno 10 pro 5g',
    'oppo|reno 10 pro+ 5g',
    'oppo|reno 11',
    'oppo|reno 11 pro',
    'oppo|reno13 5g',
    'oppo|reno13 f',
    'oppo|reno13 f 5g',
    'oppo|reno13 pro 5g',
    'oppo|reno14 5g',
    'oppo|reno14 f 5g',
    'oppo|reno14 pro 5g',
    'oppo|oneplus nord 4',
    'oppo|oneplus nord ce4 lite 5g',

    // Realme
    'realme|narzo 60x 5g',
    'realme|realme gt 2 pro',
    'realme|realme gt 3 240w',
    'realme|realme gt 5',
    'realme|realme gt 5 240w',
    'realme|realme gt 7t',
    'realme|realme gt neo',
    'realme|realme gt neo 3',
    'realme|realme gt neo 3 150w',
    'realme|realme gt neo 3t',
    'realme|realme gt neo 5',
    'realme|realme gt neo 5 240w',
    'realme|realme gt explorer master edition',
    'realme|realme 9 5g',
    'realme|realme 9 pro 5g',
    'realme|realme 9 pro+',
    'realme|realme 10 pro 5g',
    'realme|realme 10 pro+ 5g',
    'realme|realme 11 5g',
    'realme|realme 11 pro 5g',
    'realme|realme 11 pro+',
    'realme|realme 11 pro+ 5g',
    'realme|realme 11x 5g',
    'realme|realme 13 5g',
    'realme|realme 13 pro 5g',
    'realme|realme 13+ 5g',
    'realme|realme 14 5g',
    'realme|realme 14 pro 5g',
    'realme|realme p3 ultra 5g',
    'realme|rmx3771',
    'realme|rmx5061',

    // Samsung
    'samsung|galaxy a3 (2017)',
    'samsung|galaxy a5 (2017)',
    'samsung|galaxy a15 5g',
    'samsung|galaxy a16 5g',
    'samsung|galaxy a26 5g',
    'samsung|galaxy a35 5g',
    'samsung|galaxy a36 5g',
    'samsung|galaxy a42 5g',
    'samsung|galaxy a50',
    'samsung|galaxy a50s',
    'samsung|galaxy a51 5g',
    'samsung|galaxy a52',
    'samsung|galaxy a52 5g',
    'samsung|galaxy a52s 5g',
    'samsung|galaxy a53 5g',
    'samsung|galaxy a54 5g',
    'samsung|galaxy a55 5g',
    'samsung|galaxy a56 5g',
    'samsung|galaxy a71 5g',
    'samsung|galaxy a72',
    'samsung|galaxy a73 5g',
    'samsung|galaxy a80',
    'samsung|galaxy a90 5g',
    'samsung|galaxy f14 5g',
    'samsung|galaxy f34 5g',
    'samsung|galaxy f54 5g',
    'samsung|galaxy fold',
    'samsung|galaxy jump3',
    'samsung|galaxy m14 5g',
    'samsung|galaxy m15 5g',
    'samsung|galaxy m34 5g',
    'samsung|galaxy m52 5g',
    'samsung|galaxy m53 5g',
    'samsung|galaxy m54 5g',
    'samsung|galaxy m16 5g',
    'samsung|galaxy m36 5g',
    'samsung|galaxy note8',
    'samsung|galaxy note9',
    'samsung|galaxy note10',
    'samsung|galaxy note10 5g',
    'samsung|galaxy note10+',
    'samsung|galaxy note10+ 5g',
    'samsung|galaxy note10 lite',
    'samsung|galaxy note20 5g',
    'samsung|galaxy note20 ultra 5g',
    'samsung|galaxy quantum2',
    'samsung|galaxy quantum3',
    'samsung|galaxy s7',
    'samsung|galaxy s7 edge',
    'samsung|galaxy s8',
    'samsung|galaxy s8+',
    'samsung|galaxy s9 exynos',
    'samsung|galaxy s9 qualcomm',
    'samsung|galaxy s9+ exynos',
    'samsung|galaxy s9+ qualcomm',
    'samsung|galaxy s10e exynos',
    'samsung|galaxy s10e qualcomm',
    'samsung|galaxy s10 exynos',
    'samsung|galaxy s10 qualcomm',
    'samsung|galaxy s10+ exynos',
    'samsung|galaxy s10+ qualcomm',
    'samsung|galaxy s10 5g',
    'samsung|galaxy s10 lite',
    'samsung|galaxy s20',
    'samsung|galaxy s20 5g',
    'samsung|galaxy s20+',
    'samsung|galaxy s20+ 5g',
    'samsung|galaxy s20 fe',
    'samsung|galaxy s20 ultra 5g',
    'samsung|galaxy s21 5g',
    'samsung|galaxy s21 fe 5g',
    'samsung|galaxy s21+ 5g',
    'samsung|galaxy s21 ultra 5g',
    'samsung|galaxy s22 5g',
    'samsung|galaxy s22+ 5g',
    'samsung|galaxy s22 ultra 5g',
    'samsung|galaxy s23',
    'samsung|galaxy s23+',
    'samsung|galaxy s23 fe',
    'samsung|galaxy s23 ultra',
    'samsung|galaxy s24',
    'samsung|galaxy s24+',
    'samsung|galaxy s24 fe',
    'samsung|galaxy s24 ultra',
    'samsung|galaxy s25 ultra',
    'samsung|galaxy tab a9+ 5g',
    'samsung|galaxy tab active4 pro 5g',
    'samsung|galaxy tab active5',
    'samsung|galaxy tab active5 5g',
    'samsung|galaxy tab active5 pro',
    'samsung|galaxy tab active5 pro 5g',
    'samsung|galaxy tab s7',
    'samsung|galaxy tab s7 fe',
    'samsung|galaxy tab s7 fe 5g',
    'samsung|galaxy tab s7+',
    'samsung|galaxy tab s7+ lite',
    'samsung|galaxy tab s8',
    'samsung|galaxy tab s8+',
    'samsung|galaxy tab s8 ultra',
    'samsung|galaxy tab s9',
    'samsung|galaxy tab s9 5g',
    'samsung|galaxy tab s9 fe 5g',
    'samsung|galaxy tab s9 fe+',
    'samsung|galaxy tab s9 fe+ 5g',
    'samsung|galaxy tab s9 ultra',
    'samsung|galaxy tab s9 ultra 5g',
    'samsung|galaxy tab s9+',
    'samsung|galaxy tab s9+ 5g',
    'samsung|galaxy tab s10+',
    'samsung|galaxy tab s10 fe',
    'samsung|galaxy tab s10 fe 5g',
    'samsung|galaxy tab s10 fe+',
    'samsung|galaxy tab s10 fe+ 5g',
    'samsung|galaxy tab s10 ultra',
    'samsung|galaxy xcover7',
    'samsung|galaxy xcover7 pro',
    'samsung|galaxy z flip',
    'samsung|galaxy z flip 5g',
    'samsung|galaxy z flip3 5g',
    'samsung|galaxy z flip4',
    'samsung|galaxy z flip5',
    'samsung|galaxy z flip6',
    'samsung|galaxy z fold2 5g',
    'samsung|galaxy z fold3 5g',
    'samsung|galaxy z fold4',
    'samsung|galaxy z fold5',

    // Sony
    'sony|xperia ace iii',
    'sony|xperia xz premium',
    'sony|xperia xz1',
    'sony|xperia xz1 compact',
    'sony|xperia xz2',
    'sony|xperia xz2 compact',
    'sony|xperia xz2 premium',
    'sony|xperia xz3',
    'sony|xperia 1',
    'sony|xperia 1 ii',
    'sony|xperia 1 iii',
    'sony|xperia 1 iv',
    'sony|xperia 1 v',
    'sony|xperia 1 vii',
    'sony|xperia 5',
    'sony|xperia 5 ii',
    'sony|xperia 5 iii',
    'sony|xperia 5 iv',
    'sony|xperia 5 v',
    'sony|xperia pro',
    'sony|xperia pro-i',
    'sony|xperia 10 iii',
    'sony|xperia 10 iv',
    'sony|xperia 10 v',

    // Vivo
    'vivo|iqoo 9 pro',
    'vivo|iqoo 9t',
    'vivo|iqoo 11',
    'vivo|iqoo 11s',
    'vivo|iqoo 12',
    'vivo|iqoo 13',
    'vivo|iqoo neo9s pro+',
    'vivo|iqoo neo10',
    'vivo|iqoo neo 10r',
    'vivo|iqoo z7s 5g',
    'vivo|iqoo z7x 5g',
    'vivo|iqoo z9s 5g',
    'vivo|iqoo z9s pro 5g',
    'vivo|iqoo z10 5g',
    'vivo|iqoo z10x 5g',
    'vivo|s20',
    'vivo|s20 pro',
    'vivo|t2 5g',
    'vivo|t2 pro 5g',
    'vivo|t3 pro 5g',
    'vivo|t4 5g',
    'vivo|v25',
    'vivo|v25e',
    'vivo|v25 pro',
    'vivo|v27e',
    'vivo|v27 pro',
    'vivo|v29',
    'vivo|v29 lite 5g',
    'vivo|v29e',
    'vivo|v29e 5g',
    'vivo|v30 lite 5g',
    'vivo|v30 se',
    'vivo|v40 lite 5g',
    'vivo|v40 se 5g',
    'vivo|v40e',
    'vivo|v40 pro',
    'vivo|v50e',
    'vivo|v50',
    'vivo|v50 lite 5g',
    'vivo|x60 pro',
    'vivo|x80',
    'vivo|x80 lite 5g',
    'vivo|x80 pro',
    'vivo|x90',
    'vivo|x90 pro',
    'vivo|x100',
    'vivo|x100 pro',
    'vivo|x200',
    'vivo|x200 fe',
    'vivo|x200 pro',
    'vivo|x200 pro mini',
    'vivo|y27 5g',
    'vivo|y36 5g',
    'vivo|y39 5g',
    'vivo|y78 5g',
    'vivo|y100 5g',
    'vivo|y100a',
    'vivo|y200 5g',
    'vivo|y200e 5g',
    'vivo|y300 pro',

    // Xiaomi / POCO / Redmi
    'xiaomi|xiaomi 11t',
    'xiaomi|xiaomi 12',
    'xiaomi|xiaomi 12 lite',
    'xiaomi|xiaomi 12t pro',
    'xiaomi|xiaomi 12x',
    'xiaomi|xiaomi 12 pro',
    'xiaomi|xiaomi 13',
    'xiaomi|xiaomi 13 pro',
    'xiaomi|xiaomi 13t',
    'xiaomi|xiaomi 13 ultra',
    'xiaomi|xiaomi 14t',
    'xiaomi|xiaomi 14t pro',
    'xiaomi|xiaomi 15',
    'xiaomi|xiaomi 15 ultra',
    'xiaomi|xiaomi pad 6s pro 12.4',
    'xiaomi|mi 10i',
    'xiaomi|mi 10 lite',
    'xiaomi|mi 10 lite 5g',
    'xiaomi|mi 10 pro',
    'xiaomi|mi 11 pro',
    'xiaomi|mi 11 ultra',
    'xiaomi|pad 5',
    'xiaomi|pad 6',
    'xiaomi|pocophone f1',
    'xiaomi|poco f4',
    'xiaomi|poco f4 gt',
    'xiaomi|poco f5',
    'xiaomi|poco f5 pro',
    'xiaomi|poco m7 pro 5g',
    'xiaomi|poco x3 pro',
    'xiaomi|poco x4 gt',
    'xiaomi|poco x4 pro 5g',
    'xiaomi|poco x5 pro 5g',
    'xiaomi|poco x7 pro',
    'xiaomi|poco m4 pro',
    'xiaomi|redmi k40',
    'xiaomi|redmi k40s',
    'xiaomi|redmi k50 5g',
    'xiaomi|redmi k50g',
    'xiaomi|redmi k50i',
    'xiaomi|redmi k60',
    'xiaomi|redmi k60 ultra',
    'xiaomi|redmi note 7',
    'xiaomi|redmi note 9 (5g)',
    'xiaomi|redmi note 10',
    'xiaomi|redmi note 10 5g',
    'xiaomi|redmi note 10 pro max',
    'xiaomi|redmi note 11',
    'xiaomi|redmi note 11e pro',
    'xiaomi|redmi note 11 pro',
    'xiaomi|redmi note 11 pro 5g',
    'xiaomi|redmi note 11 pro+',
    'xiaomi|redmi note 11 pro+ 5g',
    'xiaomi|redmi note 11s',
    'xiaomi|redmi note 11s 5g',
    'xiaomi|redmi note 11t pro',
    'xiaomi|redmi note 11t pro+',
    'xiaomi|redmi note 12 discovery edition',
    'xiaomi|redmi note 12 pro',
    'xiaomi|redmi note 12 pro speed',
    'xiaomi|redmi note 12 pro+ 5g',
    'xiaomi|redmi note 12 turbo',
    'xiaomi|redmi note 13 pro+',
    'xiaomi|redmi note 14',
    'xiaomi|redmi note 14 5g',
    'xiaomi|redmi pad pro 5g',
    'redmi|redmi note 14',
    'redmi|redmi pad pro',
  };

  // ══════════════════════════════════════════════════════════════════════════
  /// Main check function
  /// [manufacturer] — device_info_plus se milta hai: androidInfo.manufacturer
  /// [model]        — device_info_plus se milta hai: androidInfo.model
  ///
  /// Usage:
  /// ```dart
  /// final info = await DeviceInfoPlugin().androidInfo;
  /// bool supported = ArCoreSupportChecker.isSupported(
  ///   info.manufacturer,
  ///   info.model,
  /// );
  /// ```
  // ══════════════════════════════════════════════════════════════════════════
  static bool isSupported(String manufacturer, String model) {
    final key =
        '${manufacturer.toLowerCase().trim()}|${model.toLowerCase().trim()}';
    return _supportedDevices.contains(key);
  }

  /// Sirf manufacturer ke base par check karo (partial match)
  /// Useful agar exact model pata na ho
  static bool isManufacturerSupported(String manufacturer) {
    final mfr = manufacturer.toLowerCase().trim();
    return _supportedDevices.any((key) => key.startsWith('$mfr|'));
  }
}