// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hz2r_0s9fx8pxIECMhMYZAa-0PDTUqI',
    appId: '1:517719105350:web:981a4643d207cfb434cf47',
    messagingSenderId: '517719105350',
    projectId: 'glamora-c4094',
    authDomain: 'glamora-c4094.firebaseapp.com',
    databaseURL: 'https://glamora-c4094-default-rtdb.firebaseio.com',
    storageBucket: 'glamora-c4094.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwc6NrIm23Sfs424nKxWW_xx2gse--aE',
    appId: '1:517719105350:android:eafbd2ef45ee45ff34cf47',
    messagingSenderId: '517719105350',
    projectId: 'glamora-c4094',
    databaseURL: 'https://glamora-c4094-default-rtdb.firebaseio.com',
    storageBucket: 'glamora-c4094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstdh4LoIWZ3IoVjN7A0mwrrAP9fVAsQU',
    appId: '1:517719105350:ios:c484f572c5c7273034cf47',
    messagingSenderId: '517719105350',
    projectId: 'glamora-c4094',
    databaseURL: 'https://glamora-c4094-default-rtdb.firebaseio.com',
    storageBucket: 'glamora-c4094.appspot.com',
    androidClientId: '517719105350-t1i8jdoc0h8428ta5irgjlf2hhf5gbt8.apps.googleusercontent.com',
    iosClientId: '517719105350-4gn61hjkf4020tuk16okagcov6r1cgsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.glamora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstdh4LoIWZ3IoVjN7A0mwrrAP9fVAsQU',
    appId: '1:517719105350:ios:c484f572c5c7273034cf47',
    messagingSenderId: '517719105350',
    projectId: 'glamora-c4094',
    databaseURL: 'https://glamora-c4094-default-rtdb.firebaseio.com',
    storageBucket: 'glamora-c4094.appspot.com',
    androidClientId: '517719105350-t1i8jdoc0h8428ta5irgjlf2hhf5gbt8.apps.googleusercontent.com',
    iosClientId: '517719105350-4gn61hjkf4020tuk16okagcov6r1cgsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.glamora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1hz2r_0s9fx8pxIECMhMYZAa-0PDTUqI',
    appId: '1:517719105350:web:371585c437eba9fc34cf47',
    messagingSenderId: '517719105350',
    projectId: 'glamora-c4094',
    authDomain: 'glamora-c4094.firebaseapp.com',
    databaseURL: 'https://glamora-c4094-default-rtdb.firebaseio.com',
    storageBucket: 'glamora-c4094.appspot.com',
  );
}
